<RootWidget>:

    #Botão de reproduzir
    Button:
        size_hint: .5, .09
        pos_hint: {"x": .1, "y": .1}

        text: "Reproduzir"

    #Botão de parar
    Button:
        size_hint: .5, .09
        pos_hint: {"x": .05, "y": .05}

        text: "Parar"

    #Entrada do path da musica
    TextInput:
        size_hint: 200, 50
        text: "digite o path da musica aqui"
        text_opacity: 50
        x: 50
        y: 100
